In [1]:
import json
from pathlib import Path

import pandas as pd

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 20)

# Notebooks usually run from their own folder, so find the project root.
root = Path.cwd()
if not (root / "data").exists():
    root = root.parent

files = sorted((root / "data" / "raw").glob("aqi_snapshot_*.json"))
payload = json.loads(files[-1].read_text(encoding="utf-8"))
records = [r for page in payload["pages"] for r in page["response"]["records"]]

df = pd.DataFrame(records)
print("Snapshot:", files[-1].name, "| shape:", df.shape)
df.head()

Snapshot: aqi_snapshot_20261026T072223Z.json | shape: (3738, 11)

  country  state         city                                 station          last_update    latitude   longitude pollutant_id min_value max_value avg_value
0   India  Bihar     Motihari         Gandak Colony, Motihari - BSPCB  26-10-2026 12:00:00    26.63086    84.90051         PM10        57       201       131
1   India  Bihar     Motihari         Gandak Colony, Motihari - BSPCB  26-10-2026 12:00:00    26.63086    84.90051          NH3         1         1         1
2   India  Bihar       Munger               Town Hall, Munger - BSPCB  26-10-2026 12:00:00   25.376776   86.471523           CO        77        98        88
3   India  Bihar  Muzaffarpur  MIT-Daudpur Kothi, Muzaffarpur - BSPCB  26-10-2026 12:00:00  26.1403345  85.3650192         PM10        NA        NA        NA
4   India  Bihar  Muzaffarpur  MIT-Daudpur Kothi, Muzaffarpur - BSPCB  26-10-2026 12:00:00  26.1403345  85.3650192          SO2        15        17        16

In [3]:
df.shape

(3738, 11)

In [4]:
df.head(5)

  country  state         city                                 station          last_update    latitude   longitude pollutant_id min_value max_value avg_value
0   India  Bihar     Motihari         Gandak Colony, Motihari - BSPCB  26-10-2026 12:00:00    26.63086    84.90051         PM10        57       201       131
1   India  Bihar     Motihari         Gandak Colony, Motihari - BSPCB  26-10-2026 12:00:00    26.63086    84.90051          NH3         1         1         1
2   India  Bihar       Munger               Town Hall, Munger - BSPCB  26-10-2026 12:00:00   25.376776   86.471523           CO        77        98        88
3   India  Bihar  Muzaffarpur  MIT-Daudpur Kothi, Muzaffarpur - BSPCB  26-10-2026 12:00:00  26.1403345  85.3650192         PM10        NA        NA        NA
4   India  Bihar  Muzaffarpur  MIT-Daudpur Kothi, Muzaffarpur - BSPCB  26-10-2026 12:00:00  26.1403345  85.3650192          SO2        15        17        16

In [5]:
df['state'].unique()

<StringArray>
[            'Bihar',             'Assam',    'Andhra Pradesh', 'Arunachal Pradesh',             'Delhi',        'Chandigarh',      'Chhattisgarh',           'Haryana',  'Himachal Pradesh',
 'Jammu and Kashmir',         'Jharkhand',         'Karnataka',           'Gujarat',    'Madhya Pradesh',       'Maharashtra',            'Kerala',            'Ladakh',         'Rajasthan',
            'Odisha',            'Punjab',        'Puducherry',         'Meghalaya',            'Sikkim',        'Tamil Nadu',     'Uttar Pradesh',         'Telangana',           'Tripura',
       'Uttarakhand',       'West Bengal',          'Nagaland',           'Mizoram']
Length: 31, dtype: str

In [9]:
df[df['state'] == 'Delhi'].shape

(424, 11)

In [10]:
df.columns

Index(['country', 'state', 'city', 'station', 'last_update', 'latitude', 'longitude', 'pollutant_id', 'min_value', 'max_value', 'avg_value'], dtype='str')

In [14]:
df[df['avg_value'] == 'NA'].shape

(327, 11)

In [12]:
df['avg_value'].unique()

<StringArray>
['131',   '1',  '88',  'NA',  '16',  '56',  '33',   '4',  '22',  '37',
 ...
 '193', '169', '285', '196', '223', '157', '202', '180', '217', '234']
Length: 229, dtype: str